Feature/share weight
MichielvanBeers/who-needs-to-share-the-board pull request #4
Opened 2023-06-25 12:00 UTC by DriesMeerman

* Restructured code to separate styling and logic into separate files.
* Refactored handleClick so Dom manipulation and logic are more split up

* Added weights to the random person selection so if you are picked you are less likely to be picked again.
* Included link to website on readme

2023-06-25 18:24 UTC, MichielvanBeers commented
Haha great stuff Dries! One small remark and then we are good to go. 💃🏻

2023-06-25 19:36 UTC, DriesMeerman commented
> Haha great stuff Dries! One small remark and then we are good to go. 💃🏻

Sure what exactly is the remark?

2023-06-26 04:58 UTC, MichielvanBeers commented
I put a comment on the import of the script and style sheet, since it didn't load correctly for me when using chrome. If you go to the could, you should be able to see it in line

2023-06-26 07:47 UTC, DriesMeerman commented
> I put a comment on the import of the script and style sheet, since it didn't load correctly for me when using chrome. If you go to the could, you should be able to see it in line

![image](https://github.com/MichielvanBeers/who-needs-to-share-the-board/assets/14854781/1318cc7e-bb56-4e7f-9813-094c929bcbb3)
I can't see your comment. 
I attempted to get the same error but could not reproduce it if you have any details please let me know.

2023-06-26 07:59 UTC, MichielvanBeers requested changes

2023-06-26 07:59 UTC, MichielvanBeers commented on index.html
> +    <link rel="stylesheet" href="/style.css" />
@DriesMeerman could you remove the '/' before script.js and style.css? In Chrome it fails to load them for some reason

2023-06-26 08:17 UTC, DriesMeerman commented on index.html
> +    <link rel="stylesheet" href="/style.css" />
updated

2023-06-26 19:10 UTC, MichielvanBeers approved these changes
🥳

2023-06-26 19:10 UTC, merged